/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::pin::Pin;
use std::rc::Rc;

use futures::Future;
use hyper;

use super::request as __internal_request;
use super::{configuration, Error};
use crate::models;

pub struct DefaultApiClient<C: hyper::client::connect::Connect>
where
    C: Clone + std::marker::Send + Sync + 'static,
{
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::connect::Connect> DefaultApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> DefaultApiClient<C> {
        DefaultApiClient { configuration }
    }
}

pub trait DefaultApi {
    fn api_jobsets_get(
        &self,
        project: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<models::JobsetOverviewInner>, Error>>>>;
    fn api_push_put(
        &self,
        jobsets: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<models::ApiPushPut200Response, Error>>>>;
    fn build_build_id_constituents_get(
        &self,
        build_id: i32,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<models::Build>, Error>>>>;
    fn build_build_id_get(
        &self,
        build_id: i32,
    ) -> Pin<Box<dyn Future<Output = Result<models::Build, Error>>>>;
    fn eval_eval_id_builds_get(
        &self,
        eval_id: i32,
    ) -> Pin<
        Box<
            dyn Future<
                Output = Result<Vec<std::collections::HashMap<String, models::Build>>, Error>,
            >,
        >,
    >;
    fn eval_eval_id_get(
        &self,
        eval_id: i32,
    ) -> Pin<Box<dyn Future<Output = Result<models::JobsetEval, Error>>>>;
    fn job_project_id_jobset_id_job_id_shield_get(
        &self,
        project_id: &str,
        jobset_id: &str,
        job_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
    fn jobset_project_id_jobset_id_delete(
        &self,
        project_id: &str,
        jobset_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::ProjectIdDelete200Response, Error>>>>;
    fn jobset_project_id_jobset_id_evals_get(
        &self,
        project_id: &str,
        jobset_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<models::Evaluations>, Error>>>>;
    fn jobset_project_id_jobset_id_get(
        &self,
        project_id: &str,
        jobset_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::Jobset, Error>>>>;
    fn jobset_project_id_jobset_id_put(
        &self,
        project_id: &str,
        jobset_id: &str,
        jobset: models::Jobset,
    ) -> Pin<Box<dyn Future<Output = Result<models::JobsetProjectIdJobsetIdPut200Response, Error>>>>;
    fn login_post(
        &self,
        login_post_request: models::LoginPostRequest,
    ) -> Pin<Box<dyn Future<Output = Result<models::LoginPost200Response, Error>>>>;
    fn project_id_delete(
        &self,
        id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::ProjectIdDelete200Response, Error>>>>;
    fn project_id_get(
        &self,
        id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::Project, Error>>>>;
    fn project_id_put(
        &self,
        id: &str,
        project_id_put_request: models::ProjectIdPutRequest,
    ) -> Pin<Box<dyn Future<Output = Result<models::ProjectIdPut200Response, Error>>>>;
    fn root_get(&self) -> Pin<Box<dyn Future<Output = Result<Vec<models::Project>, Error>>>>;
    fn search_get(
        &self,
        query: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<models::SearchResult, Error>>>>;
}

impl<C: hyper::client::connect::Connect> DefaultApi for DefaultApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    #[allow(unused_mut)]
    fn api_jobsets_get(
        &self,
        project: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<models::JobsetOverviewInner>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/api/jobsets".to_string());
        if let Some(ref s) = project {
            let query_value = s.to_string();
            req = req.with_query_param("project".to_string(), query_value);
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn api_push_put(
        &self,
        jobsets: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<models::ApiPushPut200Response, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/api/push".to_string());
        if let Some(ref s) = jobsets {
            let query_value = s.to_string();
            req = req.with_query_param("jobsets".to_string(), query_value);
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn build_build_id_constituents_get(
        &self,
        build_id: i32,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<models::Build>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/build/{build_id}/constituents".to_string(),
        );
        req = req.with_path_param("build_id".to_string(), build_id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn build_build_id_get(
        &self,
        build_id: i32,
    ) -> Pin<Box<dyn Future<Output = Result<models::Build, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/build/{build_id}".to_string());
        req = req.with_path_param("build_id".to_string(), build_id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn eval_eval_id_builds_get(
        &self,
        eval_id: i32,
    ) -> Pin<
        Box<
            dyn Future<
                Output = Result<Vec<std::collections::HashMap<String, models::Build>>, Error>,
            >,
        >,
    > {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/eval/{eval_id}/builds".to_string(),
        );
        req = req.with_path_param("eval_id".to_string(), eval_id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn eval_eval_id_get(
        &self,
        eval_id: i32,
    ) -> Pin<Box<dyn Future<Output = Result<models::JobsetEval, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/eval/{eval_id}".to_string());
        req = req.with_path_param("eval_id".to_string(), eval_id.to_string());
        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn job_project_id_jobset_id_job_id_shield_get(
        &self,
        project_id: &str,
        jobset_id: &str,
        job_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/job/{project_id}/{jobset_id}/{job_id}/shield".to_string(),
        );
        req = req.with_path_param("project_id".to_string(), project_id.to_string());
        req = req.with_path_param("jobset_id".to_string(), jobset_id.to_string());
        req = req.with_path_param("job_id".to_string(), job_id.to_string());
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn jobset_project_id_jobset_id_delete(
        &self,
        project_id: &str,
        jobset_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::ProjectIdDelete200Response, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/jobset/{project_id}/{jobset_id}".to_string(),
        );
        req = req.with_path_param("project_id".to_string(), project_id.to_string());
        req = req.with_path_param("jobset_id".to_string(), jobset_id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn jobset_project_id_jobset_id_evals_get(
        &self,
        project_id: &str,
        jobset_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<models::Evaluations>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/jobset/{project_id}/{jobset_id}/evals".to_string(),
        );
        req = req.with_path_param("project_id".to_string(), project_id.to_string());
        req = req.with_path_param("jobset_id".to_string(), jobset_id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn jobset_project_id_jobset_id_get(
        &self,
        project_id: &str,
        jobset_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::Jobset, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/jobset/{project_id}/{jobset_id}".to_string(),
        );
        req = req.with_path_param("project_id".to_string(), project_id.to_string());
        req = req.with_path_param("jobset_id".to_string(), jobset_id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn jobset_project_id_jobset_id_put(
        &self,
        project_id: &str,
        jobset_id: &str,
        jobset: models::Jobset,
    ) -> Pin<Box<dyn Future<Output = Result<models::JobsetProjectIdJobsetIdPut200Response, Error>>>>
    {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/jobset/{project_id}/{jobset_id}".to_string(),
        );
        req = req.with_path_param("project_id".to_string(), project_id.to_string());
        req = req.with_path_param("jobset_id".to_string(), jobset_id.to_string());
        req = req.with_body_param(jobset);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn login_post(
        &self,
        login_post_request: models::LoginPostRequest,
    ) -> Pin<Box<dyn Future<Output = Result<models::LoginPost200Response, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::POST, "/login".to_string());
        req = req.with_body_param(login_post_request);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn project_id_delete(
        &self,
        id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::ProjectIdDelete200Response, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/project/{id}".to_string());
        req = req.with_path_param("id".to_string(), id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn project_id_get(
        &self,
        id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<models::Project, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/project/{id}".to_string());
        req = req.with_path_param("id".to_string(), id.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn project_id_put(
        &self,
        id: &str,
        project_id_put_request: models::ProjectIdPutRequest,
    ) -> Pin<Box<dyn Future<Output = Result<models::ProjectIdPut200Response, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/project/{id}".to_string());
        req = req.with_path_param("id".to_string(), id.to_string());
        req = req.with_body_param(project_id_put_request);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn root_get(&self) -> Pin<Box<dyn Future<Output = Result<Vec<models::Project>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn search_get(
        &self,
        query: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<models::SearchResult, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/search".to_string());
        if let Some(ref s) = query {
            let query_value = s.to_string();
            req = req.with_query_param("query".to_string(), query_value);
        }

        req.execute(self.configuration.borrow())
    }
}
