# generate age key:
# sudo cat /etc/ssh/ssh_host_ed25519_key | nix-shell -p ssh-to-age age --run "ssh-to-age -private-key | age-keygen -y"
keys:
  - &user_nregner age1edzgfqhfrg5a6p9dgte7s8dqt87vu8a50up5mys0h34x3dsrj90qr743qw
  - &host_iapetus age1yuzxe2qmhc2kq8f9g09nkfp076fgq986pqtp20r0vcueumrw7feqrd3cx2
  - &host_server age1g2mgt0s80nc5yzkjnwmn6qwf8udnapx92vhwussjpa9d4et5v5zskgap5y
  - &host_kraken age16zk73cejuepyskjeq0625ecf727y3nmmw32qq0ta97q9e4uj2sqstq6240
  - &host_voron age1vzn4vh7xe7tqx0czgayafr208pjwegmus0l3gxn4v5yeemwch58sahxpee
creation_rules:
  - path_regex: common/.*/secrets.yaml
    key_groups:
      - age:
          - *user_nregner
          - *host_iapetus
          - *host_server
  - path_regex: machines/voron/(secrets.yaml|secrets/*)
    key_groups:
      - age:
          - *user_nregner
          - *host_voron
  - path_regex: machines/kraken/(secrets.yaml|secrets/*)
    key_groups:
      - age:
          - *user_nregner
          - *host_kraken
  - path_regex: machines/ec2-aarch64/secrets.yaml
    key_groups:
      - age:
          - *user_nregner
          - age19aerky0hut9aafgyet4pknu7r7emadgz8xq2tltjkupz0dluzf2sgsdfha
