#! /nix/store/lm10ywzflq9qfhr4fl0zqxrhiksf28ks-bash-5.2-p15/bin/bash
set -efu
export PATH=/nix/store/lm10ywzflq9qfhr4fl0zqxrhiksf28ks-bash-5.2-p15/bin:/nix/store/zzmqcgd2vrql9656a2fkwk948r38mgai-coreutils-9.3/bin:/nix/store/ha241bhagian5dbg9ddi2b6y2m449fh1-gnused-4.9/bin:/nix/store/mgqf3q536cjms4x6xisn1ilyihncvqjv-gptfdisk-1.0.9/bin:/nix/store/7wsy1hw09h006kbgl3vk8ns5g2w2nzn8-parted-3.6/bin:/nix/store/bcaaw77vp7hbx3q52yfqm5vjmv6qns44-systemd-minimal-254.6/bin:/nix/store/iy32qflmki16rp6s0pmd5wrwcpkynnk0-nix-2.18.1/bin:/nix/store/8nfyxswn3l133xiyms7qigqlv4q9f2yz-util-linux-2.39.2-bin/bin
showUsage() {
cat <<\USAGE
Usage: $script [options]

Options:
* --pre-format-files <src> <dst>
  copies the src to the dst on the VM, before disko is run
  This is useful to provide secrets like LUKS keys, or other files you need for formating
* --post-format-files <src> <dst>
  copies the src to the dst on the finished image
  These end up in the images later and is useful if you want to add some extra stateful files
  They will have the same permissions but will be owned by root:root
* --build-memory <amt>
  specify the ammount of memory that gets allocated to the build vm (in mb)
  This can be usefull if you want to build images with a more involed NixOS config
  By default the vm will get 1024M/1GB
USAGE
}

export out=$PWD
TMPDIR=$(mktemp -d); export TMPDIR
trap 'rm -rf "$TMPDIR"' EXIT
cd "$TMPDIR"

mkdir copy_before_disko copy_after_disko

while [[ $# -gt 0 ]]; do
  case "$1" in
  --pre-format-files)
    src=$2
    dst=$3
    cp --reflink=auto -r "$src" copy_before_disko/"$(echo "$dst" | base64)"
    shift 2
    ;;
  --post-format-files)
    src=$2
    dst=$3
    cp --reflink=auto -r "$src" copy_after_disko/"$(echo "$dst" | base64)"
    shift 2
    ;;
  --build-memory)
    regex="^[0-9]+$"
    if ! [[ $2 =~ $regex ]]; then
      echo "'$2' is not a number"
      exit 1
    fi
    build_memory=$2
    shift 1
    ;;
  *)
    showUsage
    exit 1
    ;;
  esac
  shift
done

export preVM=/nix/store/x0q16jqiak64vl9crc1fapw853s29lv3-preVM.sh
export postVM=/nix/store/pzrqbxzv4sd4gs1k1daczm0fykzbd2kp-postVM.sh
export origBuilder=/nix/store/iwjm3s5allzjbnqkrvjawsq4fhvgpqbb-disko-builder

build_memory=${build_memory:-1024}
QEMU_OPTS='-drive file=NIXOS_SD.raw,if=virtio,cache=unsafe,werror=report'
QEMU_OPTS+=" -m $build_memory"
export QEMU_OPTS

/nix/store/lm10ywzflq9qfhr4fl0zqxrhiksf28ks-bash-5.2-p15/bin/sh -e /nix/store/83wzbylvip3651v30n9cn175wgq62v9m-vm-run
cd /
