# https://github.com/berberman/nvfetcher?tab=readme-ov-file#keyfile

[joker]
src.github_tag = "candid82/joker"
fetch.github = "candid82/joker"

[kamp]
src.github_tag = "kyleisah/Klipper-Adaptive-Meshing-Purging"
fetch.github = "kyleisah/Klipper-Adaptive-Meshing-Purging"

[linux-rockchip]
src.git = "https://github.com/armbian/linux-rockchip.git"
src.branch = "rk-5.10-rkr6"
fetch.github = "armbian/linux-rockchip"



[elasticsearch]
src.container = "library/elasticsearch"
src.include_regex = "7\\..*"
fetch.docker = "library/elasticsearch"

[filebeat]
src.container = "elastic/filebeat"
src.include_regex = "7\\..*"
fetch.docker = "elastic/filebeat"

[kibana]
src.container = "library/kibana"
src.include_regex = "7\\..*"
fetch.docker = "library/kibana"

