# https://github.com/berberman/nvfetcher?tab=readme-ov-file#keyfile

[authbind]
# src.git = "https://github.com/Castaglia/MacOSX-authbind"
# fetch.github = "Castaglia/MacOSX-authbind"
src.git = "https://github.com/tmm1/MacOSX-authbind"
src.branch = "el-capitan"
fetch.github = "tmm1/MacOSX-authbind"

[blink-cmp]
src.github = "saghen/blink.cmp"
fetch.github = "saghen/blink.cmp"
cargo_locks = ["Cargo.lock"]

[cura-x86_64-linux]
src.github = "Ultimaker/Cura"
fetch.url = "https://github.com/Ultimaker/Cura/releases/download/$ver/UltiMaker-Cura-$ver-linux-X64.AppImage"

[flake-registry]
src.git = "https://github.com/nixos/flake-registry"
fetch.github = "nixos/flake-registry"

[hammerspoon]
src.github = "Hammerspoon/hammerspoon"
fetch.url = "https://github.com/Hammerspoon/hammerspoon/releases/download/$ver/Hammerspoon-$ver.zip"

[harper-ls]
src.github = "elijah-potter/harper"
fetch.github = "elijah-potter/harper"

[hyprland-workspaces]
src.github = "FieldofClay/hyprland-workspaces"
fetch.github = "FieldofClay/hyprland-workspaces"

[joker]
src.github_tag = "candid82/joker"
fetch.github = "candid82/joker"

[kamp]
src.github_tag = "kyleisah/Klipper-Adaptive-Meshing-Purging"
fetch.github = "kyleisah/Klipper-Adaptive-Meshing-Purging"

[krr]
src.github_tag = "robusta-dev/krr"
fetch.github = "robusta-dev/krr"

[launchk]
src.github = "mach-kernel/launchk"
fetch.github = "mach-kernel/launchk"

[lazygit]
fetch.github = "jesseduffield/lazygit"
src.github_tag = "jesseduffield/lazygit"
src.include_regex = "v0.44.1"

[linux-rockchip]
src.git = "https://github.com/armbian/linux-rockchip.git"
src.branch = "rk-5.10-rkr6"
fetch.github = "armbian/linux-rockchip"

[scroll-reverser]
src.github = "pilotmoon/Scroll-Reverser"
src.prefix = "v"
fetch.url = "https://github.com/pilotmoon/Scroll-Reverser/releases/download/v$ver/ScrollReverser-$ver.zip"
# fetch.github = "pilotmoon/Scroll-Reverser"
# git.fetchSubmodules = true

[sf-mono-nerd-font]
src.github = "epk/SF-Mono-Nerd-Font"
fetch.github = "epk/SF-Mono-Nerd-Font"
