#!/nix/store/58br4vk3q5akf4g8lx0pqzfhn47k3j8d-bash-5.2p37/bin/bash
set -o errexit
set -o nounset
set -o pipefail

export PATH="/nix/store/gm539jah0a6kqgpkbgpk7kc7vi3krznn-common-updater-scripts/bin:/nix/store/yh6qg1nsi5h2xblcr67030pz58fsaxx3-coreutils-9.6/bin:/nix/store/lqx2rv26sdndpa2vyy2vxsahj03km69z-git-2.48.1/bin:/nix/store/ya0hx71mq5jv3rwv4in7jk1d8zmbnzic-nix-2.24.13/bin:$PATH"

set -ex

url=""
branch=""
hardcode_zero_version=""
tag_format=""
tag_prefix=""
tag_converter=""
shallow_clone=""
: "${systemArg:=}"

while (( $# > 0 )); do
    flag="$1"
    shift 1
    case "$flag" in
      --url=*)
        url="${flag#*=}"
        ;;
      --branch=*)
        branch="${flag#*=}"
        ;;
      --hardcode-zero-version)
        hardcode_zero_version=1
        ;;
      --tag-format=*)
        tag_format="${flag#*=}"
        ;;
      --tag-prefix=*)
        tag_prefix="${flag#*=}"
        ;;
      --tag-converter=*)
        tag_converter="${flag#*=}"
        ;;
      --shallow-clone)
        shallow_clone=1
        ;;
      *)
        echo "$0: unknown option ‘${flag}’"
        exit 1
        ;;
    esac
done

# By default we set url to src.gitRepoUrl
if [[ -z "$url" ]]; then
    # system argument cannot be passed as 1 argument
    # shellcheck disable=SC2086
    url="$(nix-instantiate $systemArg --eval -E \
               "with import ./. {}; $UPDATE_NIX_ATTR_PATH.src.gitRepoUrl" \
        | tr -d '"')"
fi

# Get info about HEAD from a shallow git clone
tmpdir="$(mktemp -d)"

cloneArgs=()

if [[ "$shallow_clone" == "1" ]]; then
    cloneArgs+=(--depth=1)
fi

if [[ -n "$branch" ]]; then
    cloneArgs+=(--branch="$branch")
fi

git clone "${cloneArgs[@]}" "$url" "$tmpdir"
getLatestVersion() {
    git describe --tags --abbrev=0 --match "${tag_format}" 2> /dev/null || true
}

pushd "$tmpdir"
commit_date="$(git show -s --pretty='format:%cs')"
commit_sha="$(git show -s --pretty='format:%H')"
last_tag=""
if [[ -z "$hardcode_zero_version" ]]; then
    if [[ "$shallow_clone" == "1" ]]; then
        depth=100
        while (( depth < 10000 )); do
            last_tag="$(getLatestVersion)"
            if [[ -n "$last_tag" ]]; then
                break
            fi
            git fetch --depth="$depth" --tags
            depth=$(( depth * 2 ))
        done

        if [[ -z "$last_tag" ]]; then
            # To be extra sure, check if full history helps with finding a tag
            git fetch --tags
            last_tag="$(getLatestVersion)"
        fi
    else
        last_tag="$(getLatestVersion)"
    fi
    if [[ -z "$last_tag" ]]; then
        last_tag="0"
    fi
    if [[ -n "$tag_prefix" ]]; then
        echo "Stripping prefix '$tag_prefix' from tag '$last_tag'"
        last_tag="${last_tag#"${tag_prefix}"}"
    fi
    if [[ -n "$tag_converter" ]]; then
        echo "Running '$last_tag' through: $tag_converter"
        last_tag="$(echo "${last_tag}" | ${tag_converter})"
    fi
else
    last_tag="0"
fi
if [[ ! "$last_tag" =~ ^[[:digit:]] ]]; then
    echo "Last tag '$last_tag' does not start with a digit" > /dev/stderr
    exit 1
fi
new_version="$last_tag-unstable-$commit_date"
popd
# rm -rf "$tmpdir"

# update the nix expression
update-source-version \
    "$UPDATE_NIX_ATTR_PATH" \
    "$new_version" \
    --rev="$commit_sha"

