[package]
name = "gitea-github-mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
clients = { path = "./clients" }
color-eyre = { version = "0.6.3", features = ["capture-spantrace"] }
gix-config = "0.41.0"
http = "1"
tempdir = "0.3.7"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
  "fmt",
] }
url = "2.5.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.38", features = ["serde"] }
figment = { version = "0.10.19", features = ["env"] }
clap = { version = "4.5.31", features = ["derive"] }
