/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPushPut200Response {
    #[serde(rename = "jobsetsTriggered", skip_serializing_if = "Option::is_none")]
    pub jobsets_triggered: Option<Vec<String>>,
}

impl ApiPushPut200Response {
    pub fn new() -> ApiPushPut200Response {
        ApiPushPut200Response {
            jobsets_triggered: None,
        }
    }
}
