/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsetProjectIdJobsetIdPut201Response {
    /// url pointing to the webui for the created jobset
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<String>,
    /// url to the created jobset
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// name of the created jobset
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Set to \"jobset\"
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl JobsetProjectIdJobsetIdPut201Response {
    pub fn new() -> JobsetProjectIdJobsetIdPut201Response {
        JobsetProjectIdJobsetIdPut201Response {
            redirect: None,
            uri: None,
            name: None,
            r#type: None,
        }
    }
}

