/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsetProjectIdJobsetIdPut200Response {
    /// url pointing to the webui for the created jobset
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<String>,
}

impl JobsetProjectIdJobsetIdPut200Response {
    pub fn new() -> JobsetProjectIdJobsetIdPut200Response {
        JobsetProjectIdJobsetIdPut200Response {
            redirect: None,
        }
    }
}

