/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginPost200Response {
    /// user
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// full name
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    /// email
    #[serde(rename = "emailaddress", skip_serializing_if = "Option::is_none")]
    pub emailaddress: Option<String>,
    /// user roles
    #[serde(rename = "userroles", skip_serializing_if = "Option::is_none")]
    pub userroles: Option<Vec<String>>,
}

impl LoginPost200Response {
    pub fn new() -> LoginPost200Response {
        LoginPost200Response {
            username: None,
            fullname: None,
            emailaddress: None,
            userroles: None,
        }
    }
}
