/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginPostRequest {
    /// user
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// password
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl LoginPostRequest {
    pub fn new() -> LoginPostRequest {
        LoginPostRequest {
            username: None,
            password: None,
        }
    }
}
