/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIdPut201Response {
    /// URL of the created project
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// name of the project
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// URL of the created project
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<String>,
    /// type of the created resource (\"project\")
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl ProjectIdPut201Response {
    pub fn new() -> ProjectIdPut201Response {
        ProjectIdPut201Response {
            uri: None,
            name: None,
            redirect: None,
            r#type: None,
        }
    }
}

