/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIdPutRequest {
    /// name of the project
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// display name of the project
    #[serde(rename = "displayname", skip_serializing_if = "Option::is_none")]
    pub displayname: Option<String>,
    /// description of the project
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// homepage of the project
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    /// owner of the project
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// when set to true the project gets scheduled for evaluation
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// when true the project's jobsets support executing dynamically defined RunCommand hooks. Requires the server and project's configuration to also enable dynamic RunCommand.
    #[serde(rename = "enable_dynamic_run_command", skip_serializing_if = "Option::is_none")]
    pub enable_dynamic_run_command: Option<bool>,
    /// when set to true the project is displayed in the web interface
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    #[serde(rename = "declarative", skip_serializing_if = "Option::is_none")]
    pub declarative: Option<models::DeclarativeInput>,
}

impl ProjectIdPutRequest {
    pub fn new() -> ProjectIdPutRequest {
        ProjectIdPutRequest {
            name: None,
            displayname: None,
            description: None,
            homepage: None,
            owner: None,
            enabled: None,
            enable_dynamic_run_command: None,
            visible: None,
            declarative: None,
        }
    }
}

