/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIdDelete200Response {
    /// root of the Hydra instance
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<String>,
}

impl ProjectIdDelete200Response {
    pub fn new() -> ProjectIdDelete200Response {
        ProjectIdDelete200Response {
            redirect: None,
        }
    }
}

