/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIdPut200Response {
    /// URL of the created project
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<String>,
}

impl ProjectIdPut200Response {
    pub fn new() -> ProjectIdPut200Response {
        ProjectIdPut200Response { redirect: None }
    }
}
