/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchGet500Response {
    /// error message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl SearchGet500Response {
    pub fn new() -> SearchGet500Response {
        SearchGet500Response {
            error: None,
        }
    }
}

