/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildProduct {
    /// Size of the produced file
    #[serde(
        rename = "filesize",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub filesize: Option<Option<i32>>,
    /// if path is a directory, the default file relative to path to be served
    #[serde(rename = "defaultpath", skip_serializing_if = "Option::is_none")]
    pub defaultpath: Option<String>,
    /// Types of build product (user defined)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Name of the file
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// the nix store path
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// user-specified
    #[serde(rename = "subtype", skip_serializing_if = "Option::is_none")]
    pub subtype: Option<String>,
    /// sha256 hash of the file
    #[serde(
        rename = "sha256hash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sha256hash: Option<Option<String>>,
}

impl BuildProduct {
    pub fn new() -> BuildProduct {
        BuildProduct {
            filesize: None,
            defaultpath: None,
            r#type: None,
            name: None,
            path: None,
            subtype: None,
            sha256hash: None,
        }
    }
}
