/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Build {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// time when build started
    #[serde(rename = "starttime", skip_serializing_if = "Option::is_none")]
    pub starttime: Option<i32>,
    /// time when build ended
    #[serde(rename = "stoptime", skip_serializing_if = "Option::is_none")]
    pub stoptime: Option<i32>,
    /// time when the build was first created
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
    /// list of evaluations this build is part of
    #[serde(rename = "jobsetevals", skip_serializing_if = "Option::is_none")]
    pub jobsetevals: Option<Vec<i32>>,
    /// true when the build is finished
    #[serde(rename = "finished", skip_serializing_if = "Option::is_none")]
    pub finished: Option<bool>,
    /// name from the build's derivation
    #[serde(rename = "nixname", skip_serializing_if = "Option::is_none")]
    pub nixname: Option<String>,
    /// Indicates the build status:</br> <ul>  <li>0 : succeeded</li>  <li>1 : failed</li>  <li>2 : dependency failed</li>  <li>3 : aborted</li>  <li>4 : canceled by the user</li>  <li>6 : failed with output</li>  <li>7 : timed out</li>  <li>9 : aborted</li>  <li>10 : log size limit exceeded</li>  <li>11 : output size limit exceeded</li>  <li>*  : failed</li> </ul> <strong>Note:</strong>buildstatus should only be `null` if `finished` is false. 
    #[serde(rename = "buildstatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub buildstatus: Option<Option<i32>>,
    /// jobset this build belongs to
    #[serde(rename = "jobset", skip_serializing_if = "Option::is_none")]
    pub jobset: Option<String>,
    /// determines the priority with which this build will be executed (higher value means higher priority)
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// nix attribute from the nixexprpath
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<String>,
    /// filename of the drv
    #[serde(rename = "drvpath", skip_serializing_if = "Option::is_none")]
    pub drvpath: Option<String>,
    /// system this build was done for
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    /// project this build belongs to
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "buildproducts", skip_serializing_if = "Option::is_none")]
    pub buildproducts: Option<std::collections::HashMap<String, models::BuildProduct>>,
    #[serde(rename = "buildoutputs", skip_serializing_if = "Option::is_none")]
    pub buildoutputs: Option<std::collections::HashMap<String, models::BuildOutput>>,
    #[serde(rename = "buildmetrics", skip_serializing_if = "Option::is_none")]
    pub buildmetrics: Option<Box<models::BuildBuildmetrics>>,
}

impl Build {
    pub fn new() -> Build {
        Build {
            id: None,
            starttime: None,
            stoptime: None,
            timestamp: None,
            jobsetevals: None,
            finished: None,
            nixname: None,
            buildstatus: None,
            jobset: None,
            priority: None,
            job: None,
            drvpath: None,
            system: None,
            project: None,
            buildproducts: None,
            buildoutputs: None,
            buildmetrics: None,
        }
    }
}

