/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// BuildBuildmetrics : user defined build metrics from `$out/nix-support/hydra-metrics`. The file should define metrics separated by new lines using the following format:  ``` <name> <value>[ <unit>] ``` The name and unit fields are strings, the value is a float. The unit is optional.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildBuildmetrics {
    /// name of the measured build metric
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// measured value
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// unit of the measured build metric
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl BuildBuildmetrics {
    /// user defined build metrics from `$out/nix-support/hydra-metrics`. The file should define metrics separated by new lines using the following format:  ``` <name> <value>[ <unit>] ``` The name and unit fields are strings, the value is a float. The unit is optional.
    pub fn new() -> BuildBuildmetrics {
        BuildBuildmetrics {
            name: None,
            value: None,
            unit: None,
        }
    }
}
