/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildOutput {
    /// The nix store path
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl BuildOutput {
    pub fn new() -> BuildOutput {
        BuildOutput { path: None }
    }
}
