/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeclarativeInput {
    /// The file in `value` which contains the declarative spec file. Relative to the root of `value`.
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    /// The type of the declarative input.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The value of the declarative input.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl DeclarativeInput {
    pub fn new() -> DeclarativeInput {
        DeclarativeInput {
            file: None,
            r#type: None,
            value: None,
        }
    }
}

