/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Evaluations {
    /// first list of results
    #[serde(rename = "first", skip_serializing_if = "Option::is_none")]
    pub first: Option<String>,
    /// next list of results
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// last list of results
    #[serde(rename = "last", skip_serializing_if = "Option::is_none")]
    pub last: Option<String>,
    /// List of evaluations
    #[serde(rename = "evals", skip_serializing_if = "Option::is_none")]
    pub evals: Option<Vec<std::collections::HashMap<String, models::JobsetEval>>>,
}

impl Evaluations {
    pub fn new() -> Evaluations {
        Evaluations {
            first: None,
            next: None,
            last: None,
            evals: None,
        }
    }
}
