/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsetInput {
    /// name of the input
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// value of the input
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// type of input
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// whether or not to email responsible parties
    #[serde(rename = "emailresponsible", skip_serializing_if = "Option::is_none")]
    pub emailresponsible: Option<bool>,
}

impl JobsetInput {
    pub fn new() -> JobsetInput {
        JobsetInput {
            name: None,
            value: None,
            r#type: None,
            emailresponsible: None,
        }
    }
}

