/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsetOverviewInner {
    /// name of the jobset
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// name of the project
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// number of evaluations
    #[serde(rename = "nrtotal", skip_serializing_if = "Option::is_none")]
    pub nrtotal: Option<i32>,
    /// interval in seconds at which to check the jobset inputs
    #[serde(rename = "checkinterval", skip_serializing_if = "Option::is_none")]
    pub checkinterval: Option<i32>,
    /// true if the evaluation had errors
    #[serde(rename = "haserrormsg", skip_serializing_if = "Option::is_none")]
    pub haserrormsg: Option<bool>,
    /// number of scheduled evaluations
    #[serde(rename = "nrscheduled", skip_serializing_if = "Option::is_none")]
    pub nrscheduled: Option<i32>,
    /// number of failed evaluations
    #[serde(rename = "nrfailed", skip_serializing_if = "Option::is_none")]
    pub nrfailed: Option<i32>,
    /// time an error occurred during evaluation (unix time stamp)
    #[serde(rename = "errortime", skip_serializing_if = "Option::is_none")]
    pub errortime: Option<i32>,
    /// contains the error message when there was a problem fetching sources for a jobset
    #[serde(
        rename = "fetcherrormsg",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fetcherrormsg: Option<Option<serde_json::Value>>,
    /// time when build started
    #[serde(
        rename = "starttime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub starttime: Option<Option<i32>>,
    /// the last time the jobset inputs where checked to see if an evaluation needs to be scheduled (unix time stamp)
    #[serde(rename = "lastcheckedtime", skip_serializing_if = "Option::is_none")]
    pub lastcheckedtime: Option<i32>,
    /// time of the last evaluation trigger for this jobset (unix time stamp)
    #[serde(
        rename = "triggertime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub triggertime: Option<Option<i32>>,
}

impl JobsetOverviewInner {
    pub fn new() -> JobsetOverviewInner {
        JobsetOverviewInner {
            name: None,
            project: None,
            nrtotal: None,
            checkinterval: None,
            haserrormsg: None,
            nrscheduled: None,
            nrfailed: None,
            errortime: None,
            fetcherrormsg: None,
            starttime: None,
            lastcheckedtime: None,
            triggertime: None,
        }
    }
}
