/*
 * Hydra API
 *
 * Specification of the Hydra REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Jobset {
    /// the name of the jobset
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// the project this jobset belongs to
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// a description of the jobset
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// the name of the jobset input which contains the nixexprpath
    #[serde(rename = "nixexprinput", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nixexprinput: Option<Option<String>>,
    /// the path to the file to evaluate
    #[serde(rename = "nixexprpath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nixexprpath: Option<Option<String>>,
    /// contains the stderr output of the nix-instantiate command
    #[serde(rename = "errormsg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub errormsg: Option<Option<String>>,
    /// timestamp associated with errormsg
    #[serde(rename = "errortime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub errortime: Option<Option<i32>>,
    /// the last time the evaluator looked at this jobset
    #[serde(rename = "lastcheckedtime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lastcheckedtime: Option<Option<i32>>,
    /// set to the time we were triggered by a push event
    #[serde(rename = "triggertime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub triggertime: Option<Option<i32>>,
    /// 0 is disabled, 1 is enabled, 2 is one-shot, and 3 is one-at-a-time
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<i32>,
    /// when true the jobset sends emails when previously-successful builds fail
    #[serde(rename = "enableemail", skip_serializing_if = "Option::is_none")]
    pub enableemail: Option<bool>,
    /// when true the jobset supports executing dynamically defined RunCommand hooks. Requires the server and project's configuration to also enable dynamic RunCommand.
    #[serde(rename = "enable_dynamic_run_command", skip_serializing_if = "Option::is_none")]
    pub enable_dynamic_run_command: Option<bool>,
    /// when true the jobset is visible in the web frontend
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    /// email address to send notices to instead of the package maintainer (can be a comma separated list)
    #[serde(rename = "emailoverride", skip_serializing_if = "Option::is_none")]
    pub emailoverride: Option<String>,
    /// number or evaluations to keep
    #[serde(rename = "keepnr", skip_serializing_if = "Option::is_none")]
    pub keepnr: Option<i32>,
    /// interval (in seconds) in which to check for evaluation
    #[serde(rename = "checkinterval", skip_serializing_if = "Option::is_none")]
    pub checkinterval: Option<i32>,
    /// how many shares to be allocated to the jobset
    #[serde(rename = "schedulingshares", skip_serializing_if = "Option::is_none")]
    pub schedulingshares: Option<i32>,
    /// contains the error message when there was a problem fetching sources for a jobset
    #[serde(rename = "fetcherrormsg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fetcherrormsg: Option<Option<String>>,
    /// set to the time the latest evaluation started (if one is currently running)
    #[serde(rename = "startime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub startime: Option<Option<i32>>,
    /// the type of the jobset
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// the flake uri to evaluate
    #[serde(rename = "flake", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flake: Option<Option<String>>,
    /// inputs configured for this jobset
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<std::collections::HashMap<String, models::JobsetInput>>,
}

impl Jobset {
    pub fn new() -> Jobset {
        Jobset {
            name: None,
            project: None,
            description: None,
            nixexprinput: None,
            nixexprpath: None,
            errormsg: None,
            errortime: None,
            lastcheckedtime: None,
            triggertime: None,
            enabled: None,
            enableemail: None,
            enable_dynamic_run_command: None,
            visible: None,
            emailoverride: None,
            keepnr: None,
            checkinterval: None,
            schedulingshares: None,
            fetcherrormsg: None,
            startime: None,
            r#type: None,
            flake: None,
            inputs: None,
        }
    }
}

