[package]
name = "hydra-auto-upgrade"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.38"
serde = { version = "1.0.214", features = ["derive"] }
tempdir = "0.3.7"
ureq = { version = "2.10.1", features = ["json"] }
whoami = { version = "1.5.2", default-features = false }

[build-dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.38"
