name: Build flake outputs

on:
  push:
    branches:
      - main
      - next
      - build/gha
  # pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.branch }}
  cancel-in-progress: true

jobs:
  nix:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - aaarch64-darwin
          - aaarch64-linux
          - x86_64-linux
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          nix-fast-build \
            --eval-workers 4 \
            --eval-max-memory-size 1024 \
            --no-nom \
            --systems "${{ matrix.system }}" \
            --flake .#hydraJobs
      - name: add gc-root
        run: |
          gc-root add --profile "${{ github.repo }}/${{ github.branch }}" --generation "${{ github.ref }}" ./result*
