name: Run nix-update

on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: "0 16 * * 6" # min hour day-of-month month day-of-week

jobs:
  nix-update-matrix:
    runs-on: [self-hosted]
    outputs:
      attrs: ${{ steps.attrs.outputs.attrs }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          ref: next
      - id: attrs
        run: |
          echo "attrs=`nix eval .\#update-pkgs.passthru.attrs --json`" >> "$GITHUB_OUTPUT"
  nix-update:
    runs-on: [self-hosted]
    needs: nix-update-matrix
    strategy:
      matrix:
        attr: ${{ fromJSON(needs.nix-update-matrix.outputs.attrs) }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          ref: next
      - name: Run update script
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name "github-actions[bot]"
          nix run .\#update-pkgs -- ${{ matrix.attr }}
          git push
