name: Build

on:
  workflow_dispatch: # allows manual triggering
  push:
  # schedule:
  # - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00

jobs:
  check:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Run `nix flake check`
        run: nix flake check
